### ISSUE TITLE
stanleygf discord

### ISSUE THREAD

**Issue by MoistCoder** [MoistCoder/CockyGrabber#12]
@Stanley-GF u got discord?

**Comment by Stanley-GF** [comment]
Nah, i left all these illegal things, but u can contact me via stanleydev1337@gmail.com

**Comment by MoistCoder** [comment]
> Nah, i left all these illegal things, but u can contact me via stanleydev1337@gmail.com

Ok but why Discord tho

**Comment by Stanley-GF** [comment]
Cuz im kindly blacklisted, i cant create account

**Comment by MoistCoder** [comment]
> Cuz im kindly blacklisted, i cant create account

rip but then just create an account anonymously

**Comment by Stanley-GF** [comment]
Well, send me ur discord

**Comment by MoistCoder** [comment]
hash#8510
