### ISSUE TITLE
Help!

### ISSUE THREAD

**Issue by Dex0xm** [MoistCoder/CockyGrabber#15]
I'm having trouble using these cookies recovered using AsyncRat
can't import using any cookie manager
can't convert them
any idea on how to use them in bulk not one by one![IMG_20220309_135804.png](https://user-images.githubusercontent.com/89719102/157414904-516e45b9-f4fe-44de-af59-32b1bfe06fc1.png)

**Comment by MoistCoder** [comment]
No, I don't know sry, but you could try to create a bot in [selenium ](https://www.selenium.dev/) that automatically uses the EditThisCookie extension to bulk login or whatever. that is if bot programming is something for you...
