### ISSUE TITLE
Firefox passwords

### ISSUE THREAD

**Issue by Coten7** [MoistCoder/CockyGrabber#16]
![image](https://user-images.githubusercontent.com/65228298/157457227-03c097ac-c98f-49d0-b304-7370a0c22a2c.png)

**Comment by MoistCoder** [comment]
context?

**Comment by MoistCoder** [comment]
are you sure that you use the 2.1.0 from the [releases](https://github.com/MoistCoder/CockyGrabber/releases/tag/2.1.0)?

**Comment by Coten7** [comment]
![image](https://user-images.githubusercontent.com/65228298/157469124-c32b78ce-df32-48a4-9ad7-5569d9fcb09f.png)
yes

**Comment by MoistCoder** [comment]
I see the problem: the FirefoxGrabber doesn't decrypt the Logins. I'm gonna release a fixed patch later.

**Comment by rolltidehero** [comment]
Has this been fixed?

**Comment by MoistCoder** [comment]
> Has this been fixed?

No I'm sorry. Due to private reasons im currently not in my home country and can't fix this.
I will be back tho in like 5 - 7 days.
again: im sry

**Comment by rolltidehero** [comment]
No reason to apologize. Do what you gotta do :)

**Comment by MoistCoder** [comment]
Fixed in [v2.2.0](https://github.com/MoistCoder/CockyGrabber/tree/2.2.0): [Release](https://github.com/MoistCoder/CockyGrabber/releases/tag/2.2.0)
