### ISSUE TITLE
Cookie formating

### ISSUE THREAD

**Issue by Coten7** [MoistCoder/CockyGrabber#17]
How to format cookies like this?
![image](https://user-images.githubusercontent.com/65228298/157494766-ffeda4e8-4e50-46ea-9740-bf1a3bfafcdd.png)

**Comment by MoistCoder** [comment]
I would do something like that:
```cs
Console.WriteLine($"{cookie.field}    {cookie.field}    {cookie.field}")
```
I can't help you with the exact values since I don't know what the other values are referring to.
