### ISSUE TITLE
Help Me Please

### ISSUE THREAD

**Issue by SergioCupido** [MoistCoder/CockyGrabber#18]
I'm sorry but I seriously don't understand anything please can you make a video of at least 30 seconds on how to do it please

**Comment by SergioCupido** [comment]
i need your help please make a short video about installation

**Comment by MoistCoder** [comment]
It's simple. Can you tell me what exactly you don't understand from these steps:

1. Downloading CockyGrabber
2. Add CockyGrabber to your Project
3. Adding the necessary Packages

**Comment by DogusCyk** [comment]
When I used it before, it was in the discord token, but now when I build, even the exe is not coming, I don't know what to do.

**Comment by DogusCyk** [comment]
Can you make a short video for example please?

**Comment by MoistCoder** [comment]
> When I used it before, it was in the discord token, but now when I build, even the exe is not coming, I don't know what to do.

I understand that this isn't about CockyGrabber. It seems like you are inexperienced or have issues with visual studio.
And what do you mean with _"When I used it before, it was in the discord token"_?

> Can you make a short video for example please?

Probably not. It's not worth it making a video then editing it to hide possible important information about myself. and btw: my system isn't even in English so I doubt that you would understand something.

Can't you just describe your problem or at least list the steps you have already taken?

I mean it seems easy to me. It's just adding a library.
Like I've already theorized: you seem like you don't know how to use a library so it doesn't make sense to use a c# library for visual studio if you do not know how to add a reference in that environment.

**Comment by DogusCyk** [comment]
When I used another cookie stealer, I was entering the discord token, but I did not understand what to do with yours, can you tell me the steps in order?

**Comment by DogusCyk** [comment]
When I compile the solution, it does not give .exe

**Comment by DogusCyk** [comment]
Also, should I write something else?

**Comment by SergioCupido** [comment]
I open cockygrabber in visual studio and compile the solution, but when I compile, the .exe does not appear.

**Comment by MoistCoder** [comment]
It doesn't gives a exe because this isn't a executable.

This is a C#.NET class library. You can add it to your own Projects and code your own grabbers. It's not a finished grabber.

**Comment by SergioCupido** [comment]
so how to use it please help

**Comment by SergioCupido** [comment]
I don't understand these topics but I need to use your program please help me with this

**Comment by SkidderX** [comment]
yes i don't understand too how to use it can you help me

**Comment by rolltidehero** [comment]
It sounds like a bunch of you are just script-kiddies and no nothing about actual coding. 

I would suggest to learn how to use classes and libraries in your OWN project and then you will understand this toll and how to use it.

**Comment by MoistCoder** [comment]
> It sounds like a bunch of you are just script-kiddies and no nothing about actual coding.
> 
> I would suggest to learn how to use classes and libraries in your OWN project and then you will understand this toll and how to use it.

true. They are downloading finished grabbers, pasting their dc webhooks and scamming/"hacking" their friends or something.

_The sad thing is that I added a finished Webhook cookie grabber example in `/Examples/` but they are just to dumb to use it smh_
