### ISSUE TITLE
Feature Request: Grab Bookmarks & Browsing History

### ISSUE THREAD

**Issue by rolltidehero** [MoistCoder/CockyGrabber#20]
You can learn a lot from a users browsing history as well as their Bookmarks, because often times, users will use the OAuth2 "Sign-up Google" or some "Sign-up with GitHub account" instead of manually creating an account, and those do not get added to the Saved Passwords database. When you can grab their browsing history and bookmarks, then you can see a lot more.

**Comment by MoistCoder** [comment]
Yes! I was going to add bookmarks anyway, but search history grabbing is a fantastic idea!
Im gonna add it in the next update (2.2) or in version 2.3 (that is if I don't have time for additional features)

**Comment by MoistCoder** [comment]
This will need to wait for v2.3.0 since I didn't have had enough time to add it in [v2.2.0](https://github.com/MoistCoder/CockyGrabber/tree/2.2.0)

**Comment by MoistCoder** [comment]
Bookmark & History grabbing added in [v2.3.0](https://github.com/MoistCoder/CockyGrabber/tree/2.3.0)
