### ISSUE TITLE
Couldnt Load Type

### ISSUE THREAD

**Issue by pogrammerX** [MoistCoder/CockyGrabber#22]
If i try to use it there will be a exception

System.TypeLoadException: 'Could not load type 'System.Web.Util.Utf16StringValidator' from assembly 'System.Web, Version=4.0.0.0, Culture=neutral, PublicKeyToken=...'.'

i am using .net core 3.1

can anyone help me?

**Comment by MoistCoder** [comment]
CockyGrabber is currently a .Net Framework library so it doesn't work on .Net core.

I will migrate it to .Core at some point eventually but there is no major need for that right now since CockyGrabber only works on Windows.
