### ISSUE TITLE
mac check in GCM failed

### ISSUE THREAD

**Issue by zxcvgx** [MoistCoder/CockyGrabber#25]
**This is the error or issue the occurs when i try the statements**
"the error is within the attachment"
[error output.txt](https://github.com/MoistCoder/CockyGrabber/files/8521797/error.output.txt)

And this is the program it self

```
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using CockyGrabber.Grabbers;
using CockyGrabber;
using System.IO;

namespace Test_Ground
{
    internal class Program
    {
        private const string LogFilePath = "AAA.txt";
        static void Main(string[] args)
        {
            Console.Title = "Test Ground - Console Apllication";
            Console.Write("Starting Ground Work");
            Console.WriteLine("");


           // UniversalGrabber g = new UniversalGrabber(); // Create Grabber
            OperaGxGrabber g = new OperaGxGrabber();

            

            File.AppendAllText(LogFilePath, g.GetLogins().ToString()); // Append the grabbed Logins to the log file
            Console.ReadKey();

        }
    }
}

```

**Comment by zxcvgx** [comment]
And yes i installed the nugget packages

**Comment by MoistCoder** [comment]
Are you using the latest version? Is your project 86x (32bit) or 64x?

**Comment by zxcvgx** [comment]
Yes

**Comment by MoistCoder** [comment]
Is the problem only in OperaGxGrabber or other grabbers too?
Have you tried to make it work on other systems and if not can you try?

**Comment by zxcvgx** [comment]
i tried it on OperaGx but as it shows fails with the error but with the other not sure i dont have them installed in the mean time

**Comment by MoistCoder** [comment]
Are you sure you don't have edge installed? It's usually preinstalled on windows 10. What OS are you using as as I asked: Can you test it on an other system like a virtual Maschine?

**Comment by zxcvgx** [comment]
I got edge installed, Windows 11 Workstations, Same error

**Comment by zxcvgx** [comment]
im gonna try older .net framework versions ill update you later on

**Comment by zxcvgx** [comment]
the chrome cookie grabber works but on opera gx same error

**Comment by zxcvgx** [comment]
my main goal is to get OperaGx login and Cookies and History
can you make a explanitory event that does the specific command?

**Comment by MoistCoder** [comment]
I didn't test it on Windows 11 so I don't know it it does not work on it. Can you test it on win 10?

**Comment by zxcvgx** [comment]
hmm i see, let me check it

**Comment by zxcvgx** [comment]
but anyways what does the OS environment affect the decryption key?
tested on windows 10 same error

**Comment by zxcvgx** [comment]
Could it be that OperaGx took notice of the grabber?

**Comment by zxcvgx** [comment]
> 

also did it work for you?

**Comment by zxcvgx** [comment]
cause if that's the prob then it might be because the unsupported version
if that's case you should add it to the todo list

**Comment by MoistCoder** [comment]
Hmm. Idk if win11 encrypts values differently. CockyGrabber uses the WinAPI so It decrypts values based the API of windows.

However: I tested it and it works for me. I can later test it on a virtual machine with win 11 and see for myself.

But maybe it's because of Opera itself as you say. What version do you use?

**Comment by MoistCoder** [comment]
Hmm. Idk if win11 encrypts values differently. CockyGrabber uses the WinAPI so It decrypts values based the API of windows.

However: I tested it and it works for me. I can later test it on a virtual machine with win 11 and see for myself.

But maybe it's because of Opera itself as you say. What version do you use?

**Comment by MoistCoder** [comment]
It seems like it's a local problem. I tested it on win11 on a VM and it works. The same goes for my current PC which is win10.
I will close this issue for now but if there are more problems like this I will reopen it.
