### ISSUE TITLE
How do I format cookies like that (netscape type formatting)?

### ISSUE THREAD

**Issue by mrcracker392** [MoistCoder/CockyGrabber#28]
`.google.com   TRUE   /   FALSE   1671900542   AEC   AakniGNIFMwgF1eKJNFD6vtQPXYaNnGdY6KyhFY1LK4JqWoP6yh`

How can I format cookies in this format?

**Comment by mrcracker392** [comment]
and yes bro u worked great and it really helped me a lot love from India 
!!!!!!!!! THANKS

**Comment by MoistCoder** [comment]
It's basically just:

```
string formatted_cock = $"{cookieHostname}\tTRUE\t{cookiePath}\tFALSE\t{cookieExpiry}\t{cookieName}\t{cookieValue}";
```

(You need to fill in the variables since I'm on my phone right now and Blink/Gecko cookies also vary)

**Comment by mrcracker392** [comment]
THANKS !!! BOSS

 PLEASE DO A LAST FAVOR 

THE EXPIRATION_UTC I AM GETTING IS IN THIS FORM 

 ogs.google.com   False   /   True  **7/13/2022 11:36:37 PM -07:00**  OTZ  6548077_84_88_104280_84_44

WILL YOU PLEASE HELP ME WHAT SHOULD BE THE CHANGES TO THE CODE TO GET THIS FORMAT FOR EXPIRATION ???
I TRIED MY BEST TO GET THIS FORMAT BUT I AM NEW TO C # AND UNSUCCESSFUL TO GET THIS FORMAT THATS WHY I AM BACK IN THE LAST HOPE . 

.google.com	TRUE	/	FALSE	**1671900542**	AEC	AakniGNIFMwgF1eKJNFD6vtQPXYaNnGdY6KyhFY1LK4JqWoP

THANKS again

**Comment by MoistCoder** [comment]
Cookie dates are formatted in Unix/Webkit time format. Cockygrabber currently stores times in C#'s TimeDateOffset format.

It isn't really possible to convert them to one another. I would recommend to write just some random valie in them. In most of the cases the expiry date is not important anyway.

**Comment by mrcracker392** [comment]
okkk thats cool thanks BRO

cant i get this format default 2023-06-30T11:13:42.436Z
chrome  format ???
with any script or by makeing any changes to the code ???

**Comment by MoistCoder** [comment]
Sadly it's currently not possible. It will be in the next versions though.

**Comment by mrcracker392** [comment]
okk great so till who many days we need to wait for upgrade btw geco is not working i would like to contribute in geco portion ,
i will try my best to help this repo and push it 

Thanks again !!!!

**Comment by MoistCoder** [comment]
I don't know. To be honest I didn't work much on CockyGrabber in the last few days. I've kinda lost my motivation since I struggled with the custom SQLite reader class and Credit Card decrypter class.

If you know anything about how credit cards are encrypted please let me know. I've searched the whole web for any kind of documentation or documents that explain the encryption algorithm.

**Comment by mrcracker392** [comment]
I have something for you it mayhelp you 

If you are using telegram just text here ur telegram username i will send you some projects

**Comment by mrcracker392** [comment]
Even I have some custom SQLite  they will help you for sure 
And yes you are working good never loos the last hope see my self even I don't have any hope that will I be able to learn c# completely but I am try then bro you are a master creator of such a cool project the 1st day i text you was thanks remember it means a lot 😊😊
