### ISSUE TITLE
Please Help!

### ISSUE THREAD

**Issue by Log1cEXE** [MoistCoder/CockyGrabber#30]
When im using the grabber, it gives me this error:
```
System.IO.FileNotFoundException: 'Could not load file or assembly 'System.Web.Extensions, Version=4.0.0.0, Culture=neutral, PublicKeyToken=***********'. The system cannot find the file specified.'
```
Thanks.

**Comment by Log1cEXE** [comment]
^ I'm using Console Application

**Comment by MoistCoder** [comment]
It looks like you didn't add a reference to System.Web.Extensions.dll

Is your console application using the .NET Framework or is it a .NET Core application? As much as I know System.Web.Extensions is only included in the .NET Framework. To be sure about that though I'd have to be on my pc which I'm not on right now.

Can you tell me if your console app is using .NET Core?

**Comment by Log1cEXE** [comment]
I added this code:
```using System.Web.Extensions.dll;```
This is the error I got:
![image](https://user-images.githubusercontent.com/57271997/181544420-f21d83f4-0600-4eca-8d98-8f9c493fc00b.png)

**Comment by Log1cEXE** [comment]
Never mind, got it fixed
thanks!
