### ISSUE TITLE
Windows Defender Reports as Trojan

### ISSUE THREAD

**Issue by johnattrender** [MoistCoder/CockyGrabber#37]
As soon as I compile and run, Windows Defender reports the EXE file as a Trojan.  I think this is likely a false positive.  MS doesn't like us tinkering around with SQLite files from other applications.  Anyone have any idea how to make Windows Defender NOT report this?

**Comment by MoistCoder** [comment]
Yea, it's probably CockyGrabber copying and reading databases alerting Defender. Regardless of your situation, if you want to avoid such detection, I suggest looking at malware source code with antivirus bypass capability. While I'll try to fix this issue, I'm afraid there might not be another way.

**Comment by johnattrender** [comment]
Yeah that could be tricky for sure!  Thanks.
