### ISSUE TITLE
GeckoGrabber & BlinkGrabber are Unreachable.

### ISSUE THREAD

**Issue by toastbestraw** [MoistCoder/CockyGrabber#39]
I'm getting this error when trying to build the application:
```
2>CSC : error CS2001: Source file 'C:\Users\myname\Desktop\CockyGrabber-main\CockyGrabber\CockyGrabber\EngineGrabbers\GeckoGrabber.cs' could not be found.

2>CSC : error CS2001: Source file 'C:\Users\myname\Desktop\CockyGrabber-main\CockyGrabber\CockyGrabber\EngineGrabbers\BlinkGrabber.cs' could not be found.
```
Nothing has been changed in the code or folder.
Anything that could be causing this? And how to fix? Thanks.

**Comment by MoistCoder** [comment]
Are you sure that you downloaded all files correctly?

**Comment by toastbestraw** [comment]
> Are you sure that you downloaded all files correctly?

Yeah, I downloaded it using: code>download zip.
I also made a copy of it and renamed it without the "- main" name, still have the same error.

**Comment by MoistCoder** [comment]
I tried to recreate it so I downloaded the code, opened the solution (.sln) file, and built the project; it works for me.

Do you have a folder called "EngineGrabbers", are `GeckoGrabber.cs` and `BlinkGrabber.cs` in that folder, and are those files unopened/unused by any other program?

**Comment by toastbestraw** [comment]
Ok, I managed to get it to build, is the project meant to be a dll or an exe? I got a dll.

**Comment by toastbestraw** [comment]
Got it working, I think I chose the wrong file to build from. Thanks for your help :)
