### ISSUE TITLE
Possible to make exe?

### ISSUE THREAD

**Issue by toastbestraw** [MoistCoder/CockyGrabber#40]
Is this meant to build a .dll file? When I change it to build an exe file via properties, it has this error:
```
Error: CS5001	Program does not contain a static 'Main' method suitable for an entry point	CockyGrabber	C:\Users\myname\Desktop\CockyGrabber\CockyGrabber\CSC	1	Active
```
It's only successful when I build it as a .dll file, not for console window app or exe.

**Comment by MoistCoder** [comment]
Please inform yourself about libraries and what they are before trying to build one. This isn't an executable but if you're trying to build one, you will need to reference CockyGrabber and code it yourself.
