### ISSUE TITLE
System.IO.FileNotFoundException Assembly "System.Web.Extensions" could not be loaded

### ISSUE THREAD

**Issue by Thatoneguythatcodes** [MoistCoder/CockyGrabber#42]
Visual studio keeps saying the error might be because I'm using .net6.0 and not .net4, checked if I had all the nuget packages installed and I did, so if you think this is a problem with visual studio then I'll downgrade but not totally sure yet. Help would be greatly appreciated.

**Comment by Thatoneguythatcodes** [comment]
Could not load file or assembly 'system.web.extensions' Version =4.0.0.0

**Comment by MoistCoder** [comment]
You are using .NET (Core) but need to use .NET Framework as .NET doesn't have the assembly "System.Web.Extensions". The framework can be selected before creating the project:
![image](https://user-images.githubusercontent.com/77922456/213921022-3b505827-fd16-4c3a-9511-d700a29a0a69.png)
It's in german, but I think you understand what I mean.

**Comment by Thatoneguythatcodes** [comment]
Thank you mate
