### ISSUE TITLE
The gecko profile directory couldn't be found: C:\Users\user\AppData\Roaming\Mozilla\Firefox\Profiles

### ISSUE THREAD

**Issue by heapleak-official** [MoistCoder/CockyGrabber#45]
![image](https://user-images.githubusercontent.com/116805040/232259036-3f99f294-9a3b-4750-bae4-99a0aca58827.png)
![image](https://user-images.githubusercontent.com/116805040/232259045-1d5fa602-2cbc-4427-920e-018a315a5aa2.png)

if i add error handling, its not gonna crash, but its not gonna get the cookies either

tried this code:

https://github.com/MoistCoder/CockyGrabber/blob/main/Examples/RobloxCookieLogger.cs

**Comment by MoistCoder** [comment]
Have you checked if the directory truly exists and can you make a screenshot to prove it? It seems like it doesn't exist
